function gmm = train_gmm(datafile, num_mix, nIters)

% Return a GMM object using the data file generated by generate_data.m
% Example:
%   gmm = train_gmm('input_data.txt', 32, 10);

options = statset('Display','iter','MaxIter', nIters);

tic;
fprintf('Loading %s...\n',datafile);
X = load(datafile);
gmm = gmdistribution.fit(X, num_mix, 'Start', 'randSample','SharedCov',false,...
    'CovType', 'diagonal','Options', options);
toc;

%S.mu = X(1:num_mix,:);
%S.Sigma = repmat(var(X,1),[1,1,num_mix]);
%S.PComponents = ones(1,num_mix)/num_mix;
%gmm = gmdistribution.fit(X, num_mix, 'Start', S,'SharedCov',false,...
%    'CovType', 'diagonal','Options', options);
